//
//  File.swift
//
//
//  Created by 竹ノ内愛斗 on 2024/08/03.
//

import Foundation

/// Timezone enum
public enum TimeZone {
    case africa(Africa)
    case america(America)
    case antarctica(Antarctica)
    case asia(Asia)
    case atlantic(Atlantic)
    case australia(Australia)
    case europe(Europe)
    case indian(Indian)
    case pacific(Pacific)
    case etc(ETC)
    case other(Other)

    public enum Africa: String {
        case abidjan = "Africa/Abidjan"
        case algiers = "Africa/Algiers"
        case bissau = "Africa/Bissau"
        case cairo = "Africa/Cairo"
        case casablanca = "Africa/Casablanca"
        case ceuta = "Africa/Ceuta"
        case elAaiun = "Africa/El_Aaiun"
        case johannesburg = "Africa/Johannesburg"
        case juba = "Africa/Juba"
        case khartoum = "Africa/Khartoum"
        case lagos = "Africa/Lagos"
        case maputo = "Africa/Maputo"
        case monrovia = "Africa/Monrovia"
        case nairobi = "Africa/Nairobi"
        case ndjamena = "Africa/Ndjamena"
        case saoTome = "Africa/Sao_Tome"
        case tripoli = "Africa/Tripoli"
        case tunis = "Africa/Tunis"
        case windhoek = "Africa/Windhoek"
    }

    public enum America: String {
        case adak = "America/Adak"
        case anchorage = "America/Anchorage"
        case araguaina = "America/Araguaina"
        case argentinaBuenosAires = "America/Argentina/Buenos_Aires"
        case argentinaCatamarca = "America/Argentina/Catamarca"
        case argentinaCordoba = "America/Argentina/Cordoba"
        case argentinaJujuy = "America/Argentina/Jujuy"
        case argentinaLaRioja = "America/Argentina/La_Rioja"
        case argentinaMendoza = "America/Argentina/Mendoza"
        case argentinaRioGallegos = "America/Argentina/Rio_Gallegos"
        case argentinaSalta = "America/Argentina/Salta"
        case argentinaSanJuan = "America/Argentina/San_Juan"
        case argentinaSanLuis = "America/Argentina/San_Luis"
        case argentinaTucuman = "America/Argentina/Tucuman"
        case argentinaUshuaia = "America/Argentina/Ushuaia"
        case asuncion = "America/Asuncion"
        case bahia = "America/Bahia"
        case bahiaBanderas = "America/Bahia_Banderas"
        case barbados = "America/Barbados"
        case belem = "America/Belem"
        case belize = "America/Belize"
        case boaVista = "America/Boa_Vista"
        case bogota = "America/Bogota"
        case boise = "America/Boise"
        case cambridgeBay = "America/Cambridge_Bay"
        case campoGrande = "America/Campo_Grande"
        case cancun = "America/Cancun"
        case caracas = "America/Caracas"
        case cayenne = "America/Cayenne"
        case chicago = "America/Chicago"
        case chihuahua = "America/Chihuahua"
        case ciudadJuarez = "America/Ciudad_Juarez"
        case costaRica = "America/Costa_Rica"
        case cuiaba = "America/Cuiaba"
        case danmarkshavn = "America/Danmarkshavn"
        case dawson = "America/Dawson"
        case dawsonCreek = "America/Dawson_Creek"
        case denver = "America/Denver"
        case detroit = "America/Detroit"
        case edmonton = "America/Edmonton"
        case eirunepe = "America/Eirunepe"
        case elSalvador = "America/El_Salvador"
        case fortNelson = "America/Fort_Nelson"
        case fortaleza = "America/Fortaleza"
        case glaceBay = "America/Glace_Bay"
        case gooseBay = "America/Goose_Bay"
        case grandTurk = "America/Grand_Turk"
        case guatemala = "America/Guatemala"
        case guayaquil = "America/Guayaquil"
        case guyana = "America/Guyana"
        case halifax = "America/Halifax"
        case havana = "America/Havana"
        case hermosillo = "America/Hermosillo"
        case indianaIndianapolis = "America/Indiana/Indianapolis"
        case indianaKnox = "America/Indiana/Knox"
        case indianaMarengo = "America/Indiana/Marengo"
        case indianaPetersburg = "America/Indiana/Petersburg"
        case indianaTellCity = "America/Indiana/Tell_City"
        case indianaVevay = "America/Indiana/Vevay"
        case indianaVincennes = "America/Indiana/Vincennes"
        case indianaWinamac = "America/Indiana/Winamac"
        case inuvik = "America/Inuvik"
        case iqaluit = "America/Iqaluit"
        case jamaica = "America/Jamaica"
        case juneau = "America/Juneau"
        case kentuckyLouisville = "America/Kentucky/Louisville"
        case kentuckyMonticello = "America/Kentucky/Monticello"
        case laPaz = "America/La_Paz"
        case lima = "America/Lima"
        case losAngeles = "America/Los_Angeles"
        case maceio = "America/Maceio"
        case managua = "America/Managua"
        case manaus = "America/Manaus"
        case martinique = "America/Martinique"
        case matamoros = "America/Matamoros"
        case mazatlan = "America/Mazatlan"
        case menominee = "America/Menominee"
        case merida = "America/Merida"
        case metlakatla = "America/Metlakatla"
        case mexicoCity = "America/Mexico_City"
        case miquelon = "America/Miquelon"
        case moncton = "America/Moncton"
        case monterrey = "America/Monterrey"
        case montevideo = "America/Montevideo"
        case newYork = "America/New_York"
        case nome = "America/Nome"
        case noronha = "America/Noronha"
        case northDakotaBeulah = "America/North_Dakota/Beulah"
        case northDakotaCenter = "America/North_Dakota/Center"
        case northDakotaNewSalem = "America/North_Dakota/New_Salem"
        case nuuk = "America/Nuuk"
        case ojinaga = "America/Ojinaga"
        case panama = "America/Panama"
        case paramaribo = "America/Paramaribo"
        case phoenix = "America/Phoenix"
        case portauPrince = "America/Port-au-Prince"
        case portoVelho = "America/Porto_Velho"
        case puertoRico = "America/Puerto_Rico"
        case puntaArenas = "America/Punta_Arenas"
        case rankinInlet = "America/Rankin_Inlet"
        case recife = "America/Recife"
        case regina = "America/Regina"
        case resolute = "America/Resolute"
        case rioBranco = "America/Rio_Branco"
        case santarem = "America/Santarem"
        case santiago = "America/Santiago"
        case santoDomingo = "America/Santo_Domingo"
        case saoPaulo = "America/Sao_Paulo"
        case scoresbysund = "America/Scoresbysund"
        case sitka = "America/Sitka"
        case stjohns = "America/St_Johns"
        case swiftCurrent = "America/Swift_Current"
        case tegucigalpa = "America/Tegucigalpa"
        case thule = "America/Thule"
        case tijuana = "America/Tijuana"
        case toronto = "America/Toronto"
        case vancouver = "America/Vancouver"
        case whitehorse = "America/Whitehorse"
        case winnipeg = "America/Winnipeg"
        case yakutat = "America/Yakutat"
    }

    public enum Antarctica: String {
        case casey = "Antarctica/Casey"
        case davis = "Antarctica/Davis"
        case macquarie = "Antarctica/Macquarie"
        case mawson = "Antarctica/Mawson"
        case palmer = "Antarctica/Palmer"
        case rothera = "Antarctica/Rothera"
        case troll = "Antarctica/Troll"
    }

    public enum Asia: String {
        case almaty = "Asia/Almaty"
        case amman = "Asia/Amman"
        case anadyr = "Asia/Anadyr"
        case aqtau = "Asia/Aqtau"
        case aqtobe = "Asia/Aqtobe"
        case ashgabat = "Asia/Ashgabat"
        case atyrau = "Asia/Atyrau"
        case baghdad = "Asia/Baghdad"
        case baku = "Asia/Baku"
        case bangkok = "Asia/Bangkok"
        case barnaul = "Asia/Barnaul"
        case beirut = "Asia/Beirut"
        case bishkek = "Asia/Bishkek"
        case chita = "Asia/Chita"
        case choibalsan = "Asia/Choibalsan"
        case colombo = "Asia/Colombo"
        case damascus = "Asia/Damascus"
        case dhaka = "Asia/Dhaka"
        case dili = "Asia/Dili"
        case dubai = "Asia/Dubai"
        case dushanbe = "Asia/Dushanbe"
        case famagusta = "Asia/Famagusta"
        case gaza = "Asia/Gaza"
        case hebron = "Asia/Hebron"
        case hoChiMinh = "Asia/Ho_Chi_Minh"
        case hongKong = "Asia/Hong_Kong"
        case hovd = "Asia/Hovd"
        case irkutsk = "Asia/Irkutsk"
        case jakarta = "Asia/Jakarta"
        case jayapura = "Asia/Jayapura"
        case jerusalem = "Asia/Jerusalem"
        case kabul = "Asia/Kabul"
        case kamchatka = "Asia/Kamchatka"
        case karachi = "Asia/Karachi"
        case kathmandu = "Asia/Kathmandu"
        case khandyga = "Asia/Khandyga"
        case kolkata = "Asia/Kolkata"
        case krasnoyarsk = "Asia/Krasnoyarsk"
        case kuching = "Asia/Kuching"
        case macau = "Asia/Macau"
        case magadan = "Asia/Magadan"
        case makassar = "Asia/Makassar"
        case manila = "Asia/Manila"
        case nicosia = "Asia/Nicosia"
        case novokuznetsk = "Asia/Novokuznetsk"
        case novosibirsk = "Asia/Novosibirsk"
        case omsk = "Asia/Omsk"
        case oral = "Asia/Oral"
        case pontianak = "Asia/Pontianak"
        case pyongyang = "Asia/Pyongyang"
        case qatar = "Asia/Qatar"
        case qostanay = "Asia/Qostanay"
        case qyzylorda = "Asia/Qyzylorda"
        case riyadh = "Asia/Riyadh"
        case sakhalin = "Asia/Sakhalin"
        case samarkand = "Asia/Samarkand"
        case seoul = "Asia/Seoul"
        case shanghai = "Asia/Shanghai"
        case singapore = "Asia/Singapore"
        case srednekolymsk = "Asia/Srednekolymsk"
        case taipei = "Asia/Taipei"
        case tashkent = "Asia/Tashkent"
        case tbilisi = "Asia/Tbilisi"
        case tehran = "Asia/Tehran"
        case thimphu = "Asia/Thimphu"
        case tokyo = "Asia/Tokyo"
        case tomsk = "Asia/Tomsk"
        case ulaanbaatar = "Asia/Ulaanbaatar"
        case urumqi = "Asia/Urumqi"
        case ustNera = "Asia/Ust-Nera"
        case vladivostok = "Asia/Vladivostok"
        case yakutsk = "Asia/Yakutsk"
        case yangon = "Asia/Yangon"
        case yekaterinburg = "Asia/Yekaterinburg"
        case yerevan = "Asia/Yerevan"
    }

    public enum Atlantic: String {
        case azores = "Atlantic/Azores"
        case bermuda = "Atlantic/Bermuda"
        case canary = "Atlantic/Canary"
        case capeVerde = "Atlantic/Cape_Verde"
        case faroe = "Atlantic/Faroe"
        case madeira = "Atlantic/Madeira"
        case southGeorgia = "Atlantic/South_Georgia"
        case stanley = "Atlantic/Stanley"
    }

    public enum Australia: String {
        case adelaide = "Australia/Adelaide"
        case brisbane = "Australia/Brisbane"
        case brokenHill = "Australia/Broken_Hill"
        case darwin = "Australia/Darwin"
        case eucla = "Australia/Eucla"
        case hobart = "Australia/Hobart"
        case lindeman = "Australia/Lindeman"
        case lordHowe = "Australia/Lord_Howe"
        case melbourne = "Australia/Melbourne"
        case perth = "Australia/Perth"
        case sydney = "Australia/Sydney"
    }

    public enum Europe: String {
        case andorra = "Europe/Andorra"
        case astrakhan = "Europe/Astrakhan"
        case athens = "Europe/Athens"
        case belgrade = "Europe/Belgrade"
        case berlin = "Europe/Berlin"
        case brussels = "Europe/Brussels"
        case bucharest = "Europe/Bucharest"
        case budapest = "Europe/Budapest"
        case chisinau = "Europe/Chisinau"
        case dublin = "Europe/Dublin"
        case gibraltar = "Europe/Gibraltar"
        case helsinki = "Europe/Helsinki"
        case istanbul = "Europe/Istanbul"
        case kaliningrad = "Europe/Kaliningrad"
        case kirov = "Europe/Kirov"
        case kyiv = "Europe/Kyiv"
        case lisbon = "Europe/Lisbon"
        case london = "Europe/London"
        case madrid = "Europe/Madrid"
        case malta = "Europe/Malta"
        case minsk = "Europe/Minsk"
        case moscow = "Europe/Moscow"
        case paris = "Europe/Paris"
        case prague = "Europe/Prague"
        case riga = "Europe/Riga"
        case rome = "Europe/Rome"
        case samara = "Europe/Samara"
        case saratov = "Europe/Saratov"
        case simferopol = "Europe/Simferopol"
        case sofia = "Europe/Sofia"
        case tallinn = "Europe/Tallinn"
        case tirane = "Europe/Tirane"
        case ulyanovsk = "Europe/Ulyanovsk"
        case vienna = "Europe/Vienna"
        case vilnius = "Europe/Vilnius"
        case volgograd = "Europe/Volgograd"
        case warsaw = "Europe/Warsaw"
        case zurich = "Europe/Zurich"
    }

    public enum Indian: String {
        case chagos = "Indian/Chagos"
        case maldives = "Indian/Maldives"
        case mauritius = "Indian/Mauritius"
    }

    public enum Pacific: String {
        case apia = "Pacific/Apia"
        case auckland = "Pacific/Auckland"
        case bougainville = "Pacific/Bougainville"
        case chatham = "Pacific/Chatham"
        case easter = "Pacific/Easter"
        case efate = "Pacific/Efate"
        case fakaofo = "Pacific/Fakaofo"
        case fiji = "Pacific/Fiji"
        case galapagos = "Pacific/Galapagos"
        case gambier = "Pacific/Gambier"
        case guadalcanal = "Pacific/Guadalcanal"
        case guam = "Pacific/Guam"
        case honolulu = "Pacific/Honolulu"
        case kanton = "Pacific/Kanton"
        case kiritimati = "Pacific/Kiritimati"
        case kosrae = "Pacific/Kosrae"
        case kwajalein = "Pacific/Kwajalein"
        case marquesas = "Pacific/Marquesas"
        case nauru = "Pacific/Nauru"
        case niue = "Pacific/Niue"
        case norfolk = "Pacific/Norfolk"
        case noumea = "Pacific/Noumea"
        case pagoPago = "Pacific/Pago_Pago"
        case palau = "Pacific/Palau"
        case pitcairn = "Pacific/Pitcairn"
        case portMoresby = "Pacific/Port_Moresby"
        case rarotonga = "Pacific/Rarotonga"
        case tahiti = "Pacific/Tahiti"
        case tarawa = "Pacific/Tarawa"
        case tongatapu = "Pacific/Tongatapu"
    }

    public enum ETC: String {
        case gmt = "Etc/GMT"
        case gmtPlus1 = "Etc/GMT+1"
        case gmtPlus2 = "Etc/GMT+2"
        case gmtPlus3 = "Etc/GMT+3"
        case gmtPlus4 = "Etc/GMT+4"
        case gmtPlus5 = "Etc/GMT+5"
        case gmtPlus6 = "Etc/GMT+6"
        case gmtPlus7 = "Etc/GMT+7"
        case gmtPlus8 = "Etc/GMT+8"
        case gmtPlus9 = "Etc/GMT+9"
        case gmtPlus10 = "Etc/GMT+10"
        case gmtPlus11 = "Etc/GMT+11"
        case gmtPlus12 = "Etc/GMT+12"
        case gmtMinus1 = "Etc/GMT-1"
        case gmtMinus2 = "Etc/GMT-2"
        case gmtMinus3 = "Etc/GMT-3"
        case gmtMinus4 = "Etc/GMT-4"
        case gmtMinus5 = "Etc/GMT-5"
        case gmtMinus6 = "Etc/GMT-6"
        case gmtMinus7 = "Etc/GMT-7"
        case gmtMinus8 = "Etc/GMT-8"
        case gmtMinus9 = "Etc/GMT-9"
        case gmtMinus10 = "Etc/GMT-10"
        case gmtMinus11 = "Etc/GMT-11"
        case gmtMinus12 = "Etc/GMT-12"
        case gmtMinus13 = "Etc/GMT-13"
        case gmtMinus14 = "Etc/GMT-14"
        case utc = "Etc/UTC"
    }

    public enum Other: String {
        case cet = "CET"
        case cst6cdt = "CST6CDT"
        case eet = "EET"
        case est = "EST"
        case est5edt = "EST5EDT"
        case hst = "HST"
        case met = "MET"
        case mst = "MST"
        case mst7mdt = "MST7MDT"
        case pst8pdt = "PST8PDT"
        case wet = "WET"
    }

    var stringValue: String {
        switch self {
        case .africa(let tz): return tz.rawValue
        case .america(let tz): return tz.rawValue
        case .antarctica(let tz): return tz.rawValue
        case .asia(let tz): return tz.rawValue
        case .atlantic(let tz): return tz.rawValue
        case .australia(let tz): return tz.rawValue
        case .europe(let tz): return tz.rawValue
        case .indian(let tz): return tz.rawValue
        case .pacific(let tz): return tz.rawValue
        case .etc(let tz): return tz.rawValue
        case .other(let tz): return tz.rawValue
        }
    }
}
